version: '3.7'
services:
  mssql-server:
    container_name: mssql
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "178:1433"
    environment:
      MSSQL_SA_PASSWORD : "Abcdefg-12345"
      ACCEPT_EULA : "Y"
    volumes:
      - ./data:/var/opt/mssql/data
    